# general.working_directory = "repos"

[window]
opacity = 0.8
padding.x = 20
padding.y = 20
decorations = "Full"
decorations_theme_variant = "Dark"
blur = true

[general]
import = [
    "~/dotfiles/alacritty/.config/alacritty/themes/themes/hyper.toml"
]

[font]
normal = { family = "Monocraft", style = "Regular" }
